# Generated by Django 5.1.6 on 2025-03-05 05:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_alter_chart_charttype_alter_pack_style'), ('api', '0003_remove_song_path_chart_taps_song_songlength'), ('api', '0004_pack_banner'), ('api', '0005_remove_pack_type_song_filename'), ('api', '0006_pack_types_alter_song_filename')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('size', models.IntegerField()),
                ('scanned', models.BooleanField()),
                ('sha1sum', models.CharField(max_length=40)),
                ('style', models.JSONField(default=list)),
                ('substyle', models.CharField(blank=True, choices=[('technical', 'Technical'), ('mods', 'Mods'), ('stamina', 'Stamina'), ('dump', 'Dump')], max_length=32, null=True)),
                ('sync', models.CharField(choices=[('0', 'Null'), ('9ms', 'Nine'), ('other', 'Other'), ('mixed', 'Mixed')], default='0', max_length=32, null=True)),
                ('extras', models.BooleanField()),
                ('min_version', models.CharField(choices=[('dwi', 'Dwi'), ('Stepmania 3.9', 'Sm39'), ('OpenITG', 'Oitg'), ('Stepmania 5', 'Sm5'), ('outfox', 'Outfox')], default='Stepmania 3.9', max_length=32, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_scanned', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner', models.CharField(blank=True, max_length=64)),
                ('types', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('banner', models.CharField(blank=True, max_length=255, null=True)),
                ('bpms', models.CharField(blank=True, max_length=100, null=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='api.pack')),
                ('songlength', models.FloatField(default=0)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charttype', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('meter', models.IntegerField()),
                ('lastsecondhint', models.FloatField()),
                ('npspeak', models.FloatField()),
                ('npsgraph', models.JSONField()),
                ('chartkey', models.CharField(max_length=64, unique=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='api.song')),
                ('taps', models.JSONField(default=dict)),
            ],
        ),
    ]
