# Generated by Django 4.2.11 on 2025-03-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0006_pack_types_alter_song_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='size',
            field=models.BigIntegerField(),
        ),
    ]
