# Generated by Django 4.2.11 on 2025-03-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pack_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='credit',
            field=models.CharField(default=[], max_length=255),
            preserve_default=False,
        ),
    ]
