# Generated by Django 4.2.11 on 2025-03-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pack_authors_song_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='author',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='credit',
            field=models.JSONField(default=list),
        ),
    ]
