# Generated by Django 4.2.11 on 2025-03-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_song_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='npsgraph',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chart',
            name='taps',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='pack',
            name='substyle',
            field=models.CharField(blank=True, choices=[('technical', 'Technical'), ('mods', 'Mods'), ('stamina', 'Stamina'), ('dump', 'Dump'), ('all around', 'Allaround')], max_length=32, null=True),
        ),
    ]
