# Generated by Django 4.2.11 on 2025-03-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_pack_authors_alter_chart_chartkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='authors',
            field=models.JSONField(default=list),
        ),
    ]
