# Generated by Django 4.2.11 on 2025-03-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pack_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artisttranslit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='subtitletranslit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='titletranslit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
