# Generated by Django 4.2.11 on 2025-04-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_song_artisttranslit_song_subtitletranslit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='author',
            field=models.CharField(max_length=128),
        ),
    ]
