# Generated by Django 4.2.11 on 2025-04-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_chartdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
