# Generated by Django 4.2.11 on 2025-04-08 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_song_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='chart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chartdata', to='api.chart'),
        ),
    ]
