# Generated by Django 4.2.11 on 2025-04-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_chartdata_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='packType',
            field=models.CharField(blank=True, choices=[('ddr', 'Ddr'), ('itg', 'Itg'), ('keyboard', 'Keyboard'), ('index', 'Index'), ('spread', 'Spread'), ('mixed', 'Mixed')], max_length=32, null=True),
        ),
    ]
