# Generated by Django 4.2.11 on 2025-04-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_pack_packtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
