# Generated by Django 4.2.11 on 2025-08-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_pack_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='altname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='packType',
            field=models.CharField(blank=True, choices=[('pad', 'Pad'), ('ddr', 'Ddr'), ('itg', 'Itg'), ('keyboard', 'Keyboard'), ('index', 'Index'), ('spread', 'Spread'), ('mixed', 'Mixed')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='sync',
            field=models.CharField(choices=[('null', 'Null'), ('9ms', 'Nine'), ('other', 'Other'), ('mixed', 'Mixed'), ('n/a', 'Na')], default='n/a', max_length=32, null=True),
        ),
    ]
