# Generated by Django 6.0 on 2026-01-05 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_pack_altname_alter_pack_packtype_alter_pack_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chartkey',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='chart',
            name='charttype',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pack',
            name='authors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ScanPacksRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packdir', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('q_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
